### PR TITLE
feat: add labels to the issue listing

### PR DESCRIPTION
**Pull request by martinpovolny**
feat: add labels to the issue listing

add the ability to display issue labels in the issue list

```
jira issue list -s~Closed --columns KEY,TYPE,SUMMARY,STATUS,ASSIGNEE,CREATED,labels
```

### CODE REVIEW

**Comment by martinpovolny** [comment]
@ankitpokhrel : please, let me know if I shall
 * update the tests to pass or
 * make the default list of columns not include the "labels"

**Comment by ankitpokhrel** [comment]
Hi @martinpovolny, I think we can fix the tests.

**Comment by martinpovolny** [comment]
@ankitpokhrel : I have updated the tests and also the sprint view code.

**Review by ankitpokhrel — APPROVED** [review]
This looks good. Thank you @martinpovolny 🎉

**Pull request merged**
